In [30]:
import pandas as pd
import gspread
import copy
import os
from pathlib import Path
import matplotlib.pyplot as plt
from oauth2client.service_account import ServiceAccountCredentials
from datetime import datetime
from datetime import timedelta

# glibber glabber that I copied and pasted
scope = ['https://spreadsheets.google.com/feeds']
credentials = ServiceAccountCredentials.from_json_keyfile_name('practice-log-444917-d375b6889398.json', scope)
gc = gspread.authorize(credentials)

# spreadsheet_key = '1AgQWFFgXEYRAtokWU8NNDdGKy5R7DYBoPMFukrRtMiA' # This is the test sheet
spreadsheet_key = '13CdEbddbIDDHdCVU9IvpHQzSB4lJroJ36Riufl5uvTk' # This is the real sheet
book = gc.open_by_key(spreadsheet_key)

In [31]:
# Studio in order of grade then alphabetical by last name
studio_names = ['Jaime Cardenas', 'Anna Desfor', 'Matt Schneider', 'Tanner Day', 'Trevor Maliborski', 'Adina Shaikh', 'Dylan Chapman', 'Joshua Dieter',
          'Van Maxwell', 'Cadie Strahota', 'Nate Dreyfus', 'Ravlin Frantz', 'Ellis Goeden', 'Kendal Schreiber', 'Alex Seitler',
          'Cooper Atkinson', 'Aaron Dieter', 'Ryan Gomez', 'Annabelle Nault', 'Marley Van Domelan','Eleanor Peska', 'Aidan Lishner', 'Pete Navratil', 'Nick Ruplinger',
          'Adam Hein', 'Colin Mortimore', 'Dante Baker', 'Jack Johnson', 'John Griffin']

In [32]:
# database of names and nicknames
names = {}

# add first names to database
for full_name in studio_names:
    first_name = full_name.split(' ')[0].lower()
    names[full_name] = [first_name]

names['Cooper Atkinson'].append('coop')
names['Ravlin Frantz'].append('rav')
names['Joshua Dieter'].append('josh')

In [33]:
# grade by name

name_grade = {}

# DMA
for name in ['Jaime Cardenas', 'Anna Desfor', 'Matt Schneider', 'Jack Johnson']:
    name_grade[name] = 'DMA'

# Master
for name in []:
    name_grade[name] = 'Masters'

# Super Senior
for name in []:
    name_grade[name] = 'Super Senior'

# Graduated
for name in ['Dylan Chapman', 'Joshua Dieter', 'Van Maxwell', 'Cadie Strahota', 'Tanner Day', 'Trevor Maliborski', 'Adina Shaikh']:
    name_grade[name] = 'Graduated'

# Senior
for name in ['Ravlin Frantz', 'Ellis Goeden', 'Kendal Schreiber', 'Alex Seitler', 'Nate Dreyfus']:
    name_grade[name] = 'Senior'
    
# Junior
for name in ['Cooper Atkinson', 'Aaron Dieter', 'Ryan Gomez', 'Annabelle Nault', 'Marley Van Domelan', 'Eleanor Peska']:
    name_grade[name] = 'Junior'

# Sophomore
for name in ['Aidan Lishner', 'Pete Navratil', 'Nick Ruplinger']:
    name_grade[name] = 'Sophomore'

# Freshman
for name in ['Adam Hein', 'Colin Mortimore', 'Dante Baker', 'John Griffin']:
    name_grade[name] = 'Freshman'

In [34]:
timeframes = ['7:00 AM','7:15 AM','7:30 AM','7:45 AM','8:00 AM','8:15 AM','8:30 AM','8:45 AM','9:00 AM','9:15 AM','9:30 AM','9:45 AM', 
'10:00 AM','10:15 AM','10:30 AM','10:45 AM','11:00 AM','11:15 AM','11:30 AM','11:45 AM','12:00 PM','12:15 PM','12:30 PM','12:45 PM','1:00 PM', \
'1:15 PM','1:30 PM','1:45 PM','2:00 PM','2:15 PM','2:30 PM','2:45 PM','3:00 PM','3:15 PM','3:30 PM','3:45 PM','4:00 PM','4:15 PM','4:30 PM','4:45 PM', \
'5:00 PM','5:15 PM','5:30 PM','5:45 PM','6:00 PM','6:15 PM','6:30 PM','6:45 PM','7:00 PM','7:15 PM','7:30 PM','7:45 PM','8:00 PM','8:15 PM','8:30 PM', \
'8:45 PM','9:00 PM','9:15 PM','9:30 PM','9:45 PM','10:00 PM','10:15 PM','10:30 PM','10:45 PM']

In [35]:
# name_grabber : function to determine if a name is in the studio, returns full name or name that was inputted
def name_grabber(cell):
    name = None
    for full_name, names_list in names.items():
        for curr_name in names_list:
            if curr_name.strip().lower() == cell.strip().lower():
                name = full_name
                break
    if name == None:
        return cell
    else:
        return name

In [36]:
# rooms
rooms = ["Studio", "1401", "1407", "1409", "1413", "1414", "1416", "1417", "1418"]

In [37]:
# read single week; returns dict with {room: df}
def read_single_week(week, path):
    week_path = path + week
    compiled_data = {}
    for room_csv in os.listdir(week_path):
        room = room_csv.split('.')[0]
        df = pd.read_csv("data/" + week + "/"+ room_csv).fillna('')
        df = df.set_index('Time').rename_axis('Time')
        compiled_data[room] = df
    return compiled_data

In [38]:
# function takes week of format 'MM_DD_YY' and returns datetime object
def week_to_dt(week):
    times = week.split('_')
    month = int(times[0])
    day = int(times[1])
    year = int("20" + times[2])
    return datetime(year, month, day)

days_of_the_week = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun']

# function takes week and returns list of 7 days starting from given weekdate
def gen_dates(week):
    week_dates = {}
    first_day = week_to_dt(week)
    for num in range(0,7):
        week_dates[days_of_the_week[num]] = (first_day + timedelta(days=num))
    return week_dates

In [39]:
# read all weeks data, combined into one
compiled_data = {}
path = "/Users/aaron/Documents/Python Scripts/Practice Log/data/"
weeks = os.listdir(path)
for week in weeks:
    dict = read_single_week(week, path)
    for room_df in dict:
        if room_df not in compiled_data: # initialize data
            compiled_data[room_df] = []
        compiled_data[room_df].append(dict[room_df].rename(columns=gen_dates(week)))

# concat all weeks together by room
for room in compiled_data:
    compiled_data[room] = pd.concat(compiled_data[room], axis=1)
    compiled_data[room] = compiled_data[room].sort_index(axis=1)
    
# compiled_data['Studio']

In [40]:
# normalize entries
normalized_entries = []

for room in compiled_data:
    for day in compiled_data[room]:
        for index, entry in compiled_data[room][day].items():
            if entry == "":
                continue
            time = index
            person = name_grabber(entry)
            grade = 'Unknown'
            if person in name_grade:
                grade = name_grade[person]
        
            n_entry = {
                "room": room,
                "datetime": datetime.combine(day, datetime.strptime(time, "%I:%M %p").time()),
                "day": day,
                "time": time,
                "grade": grade,
                "person": person,
                "is_lesson": person == "LESSONS",
                "is_other": person == entry
            }
            normalized_entries.append(n_entry)

entries = pd.DataFrame(normalized_entries)

In [41]:
# save entries

# change date for every use

entries.to_csv(
    "entries/entries-8_22_26.csv",
    index=False
)

In [42]:
# entries_by_person = entries.groupby(["person"]).size()
# entries_by_person_by_time = entries.groupby(["person",'time']).size()
# entries_by_time = entries.groupby(['time']).size()
# entries_by_room = entries.groupby(['room']).size()
# entries_by_room_by_person = entries.groupby(['room','person']).size()
# entries_by_person_by_room = entries.groupby(['person','room']).size()
# entries_by_room_wo_lessons = entries[entries['is_lesson'] == False].groupby(['room']).size()
# entries_by_day = entries.groupby(["day"]).size()
# entries_by_person_by_day = entries_by_day = entries.groupby(['person',"day"]).size()
# other_entries = entries[entries['is_other']]

In [43]:
# entries to time conversion function
def entries_to_time(row):
    hours = row['Entries']*15/60
    hours_mins = str(hours).split('.')
    if int(hours_mins[0]) == 0:
        return str(int(float('.'+hours_mins[1])*60)) + 'mins'
    else: 
        return str(hours_mins[0]) + 'hrs ' + str(int(float('.'+hours_mins[1])*60)) + 'mins'

def entries_to_time_reg(entries):
    hours = entries*15/60
    hours_mins = str(hours).split('.')
    if int(hours_mins[0]) == 0:
        return str(int(float('.'+hours_mins[1])*60)) + 'mins'
    else: 
        return str(hours_mins[0]) + 'hrs ' + str(int(float('.'+hours_mins[1])*60)) + 'mins'

In [44]:
# entries to time per day (assume 7 days a week)
def entries_to_time_p_day(row):
    hours = row['Entries']*15/60/(len(entries.groupby(['person',"day"]).size()[row['Name']]))  # divide by the 7 days in the week
    hours_mins = str(hours).split('.')
    if int(hours_mins[0]) == 0:
        return str(int(float('.'+hours_mins[1])*60)) + 'mins'
    else: 
        return str(hours_mins[0]) + 'hrs ' + str(int(float('.'+hours_mins[1])*60)) + 'mins'

In [45]:
def fav(row, series):
    try:
        person_series = series.loc[row["Name"]]
    except KeyError:
        return "N/A"

    max_val = person_series.max()
    favorites = person_series[person_series == max_val]

    if len(favorites) == 1:
        return favorites.index[0], entries_to_time_reg(max_val)

    return [(idx, entries_to_time_reg(max_val)) for idx in favorites.index]

In [46]:
def convert_datetime(row):
    entry = row['Most Practicing in a Day']

    if entry == 'N/A':
        return entry
    
    if type(entry) == list:
        result = []
        for tup in entry:
            dt_ob = tup[0]
            formatted_string = dt_ob.strftime("%m-%d-%Y")
            result.append((formatted_string,tup[1]))
    else:
        dt_ob = row['Most Practicing in a Day'][0]
        formatted_string = dt_ob.strftime("%m-%d-%Y")
        result = (formatted_string,row['Most Practicing in a Day'][1])
    return result

In [49]:
# Using normalized entries to create summarized stats

perc_stats = entries.groupby(["person","grade"]).size().reset_index()
perc_stats.columns = ['Name',"Grade",'Entries']

# Time Practiced
perc_stats['Time Practiced'] = perc_stats.apply(entries_to_time, axis=1)

# Time/Day
perc_stats['AVG Time per Day'] = perc_stats.apply(entries_to_time_p_day, axis=1)

# Favorite Practice Timeframe
perc_stats['Favorite Practice Timeframe'] = perc_stats.apply(fav, args = (entries.groupby(["person",'time']).size(),), axis=1)

# Favorite Practice Room
perc_stats['Favorite Practice Room'] = perc_stats.apply(fav, args = (entries.groupby(['person','room']).size(),), axis=1)

perc_stats['Most Practicing in a Day'] = perc_stats.apply(fav, args = (entries.groupby(['person',"day"]).size(),), axis=1)
perc_stats['Most Practicing in a Day'] = perc_stats.apply(convert_datetime, axis=1)

perc_stats

,Name,Grade,Entries,Time Practiced,AVG Time per Day,Favorite Practice Timeframe,Favorite Practice Room,Most Practicing in a Day
0,,Unknown,3,45mins,22mins,"[(2:30 PM, 15mins), (2:45 PM, 15mins), (7:15 P...","(1418, 30mins)","(01-27-2026, 30mins)"
1,,Unknown,1,15mins,15mins,"(5:45 PM, 15mins)","(Studio, 15mins)","(12-09-2025, 15mins)"
2,(Pete) mba out,Unknown,6,1hrs 30mins,1hrs 30mins,"[(11:00 AM, 15mins), (11:15 AM, 15mins), (11:3...","(1414, 1hrs 30mins)","(12-08-2025, 1hrs 30mins)"
3,(disanza in),Unknown,1,15mins,15mins,"(12:30 PM, 15mins)","(Studio, 15mins)","(03-12-2026, 15mins)"
4,(disanza in),Unknown,4,1hrs 0mins,1hrs 0mins,"[(12:00 PM, 15mins), (12:15 PM, 15mins), (12:4...","(Studio, 1hrs 0mins)","(03-12-2026, 1hrs 0mins)"
...,...,...,...,...,...,...,...,...
254,vibe out/kit out,Unknown,16,4hrs 0mins,2hrs 0mins,"[(1:00 PM, 30mins), (1:15 PM, 30mins), (1:30 P...","(1409, 4hrs 0mins)","[(04-17-2026, 2hrs 0mins), (04-24-2026, 2hrs 0..."
255,vibe out/kit out (Josh),Unknown,3,45mins,45mins,"[(3:00 PM, 15mins), (3:15 PM, 15mins), (3:30 P...","(1409, 45mins)","(04-25-2026, 45mins)"
256,xylo out,Unknown,55,13hrs 45mins,2hrs 45mins,"(3:30 PM, 1hrs 15mins)","(1417, 8hrs 0mins)","(04-29-2026, 6hrs 15mins)"
257,xylo out/Annabelle,Unknown,4,1hrs 0mins,1hrs 0mins,"[(1:30 PM, 15mins), (1:45 PM, 15mins), (2:00 P...","(1417, 1hrs 0mins)","(04-29-2026, 1hrs 0mins)"
258,zaidan,Unknown,1,15mins,15mins,"(3:45 PM, 15mins)","(Studio, 15mins)","(02-08-2026, 15mins)"

In [50]:
# save perc_stats

# change date for every use

perc_stats.to_csv(
    "perc_stats/perc_stats-8_22_26.csv",
    index=False
)

In [54]:
perc_stats[(perc_stats["Favorite Practice Room"].str[0] == "1409") & (perc_stats["Grade"] != "Unknown")]

,Name,Grade,Entries,Time Practiced,AVG Time per Day,Favorite Practice Timeframe,Favorite Practice Room,Most Practicing in a Day
40,Cadie Strahota,Graduated,292,73hrs 0mins,1hrs 16mins,"[(11:30 AM, 7hrs 15mins), (11:45 AM, 7hrs 15mi...","(1409, 23hrs 45mins)","[(12-09-2025, 2hrs 0mins), (01-22-2026, 2hrs 0..."
48,Cooper Atkinson,Junior,253,63hrs 15mins,1hrs 19mins,"(1:15 PM, 3hrs 45mins)","(1409, 32hrs 0mins)","(01-29-2026, 3hrs 0mins)"
54,Dylan Chapman,Graduated,516,129hrs 0mins,1hrs 33mins,"(1:45 PM, 8hrs 0mins)","(1409, 38hrs 45mins)","(03-15-2026, 3hrs 30mins)"
56,Eleanor Peska,Junior,520,130hrs 0mins,1hrs 42mins,"(4:30 PM, 5hrs 15mins)","(1409, 56hrs 0mins)","(04-16-2026, 3hrs 45mins)"
115,Marley Van Domelan,Junior,883,220hrs 45mins,2hrs 23mins,"(2:15 PM, 9hrs 0mins)","(1409, 62hrs 15mins)","(01-29-2026, 6hrs 45mins)"
131,Nick Ruplinger,Sophomore,1248,312hrs 0mins,2hrs 17mins,"[(11:30 AM, 10hrs 0mins), (11:45 AM, 10hrs 0mi...","(1409, 82hrs 0mins)","(03-22-2026, 6hrs 0mins)"
148,Ravlin Frantz,Senior,578,144hrs 30mins,1hrs 36mins,"(10:15 AM, 6hrs 0mins)","(1409, 41hrs 45mins)","(02-28-2026, 4hrs 30mins)"
150,Ryan Gomez,Junior,163,40hrs 45mins,1hrs 41mins,"(10:30 AM, 2hrs 30mins)","(1409, 28hrs 45mins)","(12-14-2025, 3hrs 30mins)"
176,Trevor Maliborski,Graduated,627,156hrs 45mins,1hrs 54mins,"[(5:00 PM, 10hrs 15mins), (5:15 PM, 10hrs 15mi...","(1409, 107hrs 0mins)","(04-03-2026, 4hrs 45mins)"

In [72]:
sorted_perc_stats = perc_stats.sort_values('Entries', ascending = False)

entries_by_grade = sorted_perc_stats.groupby('Grade').agg(
    Count=('Entries', 'count'),
    Entries=('Entries', 'sum')
)

entries_by_grade['avg'] = entries_by_grade['Entries']/entries_by_grade['Count']

# resort by grade using categories
entries_by_grade.index = entries_by_grade.index.astype("category")
new_order = ["Freshman", "Sophomore", "Junior", "Senior", "Graduated", "Super Senior", "Masters", "DMA", "Unknown"]

entries_by_grade = pd.merge(entries_by_grade, pd.DataFrame({"Grade": new_order}), on="Grade", how="right").fillna(0)

entries_by_grade

          Grade  Count  Entries         avg
0      Freshman    1.0     80.0   80.000000
1     Sophomore    3.0   2365.0  788.333333
2        Junior    6.0   3237.0  539.500000
3        Senior    5.0   3163.0  632.600000
4     Graduated    7.0   2796.0  399.428571
5  Super Senior    0.0      0.0    0.000000
6       Masters    0.0      0.0    0.000000
7           DMA    4.0   2152.0  538.000000
8       Unknown  233.0   3964.0   17.012876

In [73]:
sorted_perc_stats[sorted_perc_stats["Grade"] == "Junior"]

,Name,Grade,Entries,Time Practiced,AVG Time per Day,Favorite Practice Timeframe,Favorite Practice Room,Most Practicing in a Day
115,Marley Van Domelan,Junior,883,220hrs 45mins,2hrs 23mins,"(2:15 PM, 9hrs 0mins)","(1409, 62hrs 15mins)","(01-29-2026, 6hrs 45mins)"
9,Aaron Dieter,Junior,877,219hrs 15mins,1hrs 39mins,"(2:00 PM, 12hrs 0mins)","(Studio, 67hrs 15mins)","(07-01-2026, 5hrs 0mins)"
29,Annabelle Nault,Junior,541,135hrs 15mins,1hrs 51mins,"(3:30 PM, 6hrs 45mins)","(1414, 38hrs 45mins)","(01-27-2026, 3hrs 45mins)"
56,Eleanor Peska,Junior,520,130hrs 0mins,1hrs 42mins,"(4:30 PM, 5hrs 15mins)","(1409, 56hrs 0mins)","(04-16-2026, 3hrs 45mins)"
48,Cooper Atkinson,Junior,253,63hrs 15mins,1hrs 19mins,"(1:15 PM, 3hrs 45mins)","(1409, 32hrs 0mins)","(01-29-2026, 3hrs 0mins)"
150,Ryan Gomez,Junior,163,40hrs 45mins,1hrs 41mins,"(10:30 AM, 2hrs 30mins)","(1409, 28hrs 45mins)","(12-14-2025, 3hrs 30mins)"

In [ ]:
# filter by studio members and reset the index 
studio_stats = sorted_perc_stats[sorted_perc_stats["Grade"] != "Unknown"].reset_index(drop=True)
studio_stats.index = studio_stats.index + 1
studio_stats

In [ ]:
other_stats = sorted_perc_stats[sorted_perc_stats["Grade"] == "Unknown"]
# other_stats[75:125]

In [ ]:
mar_out_stats = other_stats[other_stats["Name"].str.contains("marimba out", case=False, na=False)]
mar_out_stats["Time Practiced"]

# mar_out_stats barplot
plt.bar(mar_out_stats["Name"], mar_out_stats["Entries"])
plt.xlabel("Marimba out type")
plt.xticks(rotation = 70)
plt.ylabel("Number of Entries")
plt.title("Marimba out vs. number of entries")
plt.show()

In [ ]:
sum(mar_out_stats["Entries"])*15/60

In [ ]:
# # overall stats

# max_room_val = max(entries_by_room.values())
# max_room = [k for k, v in entries_by_room.items() if v == max_room_val]
# if len(max_room) == 1:
#     max_room = max_room[0]

# overall_stats = pd.Series({"Total Practice Time": entries_to_time_reg(sum(perc_stats["Entries"])), 
#                            "Most Used Room": max_room + ": " + entries_to_time_reg(max_room_val)})

# overall_stats

In [ ]:
# rooms_df = pd.DataFrame({"Room": rooms})

# def room_lb(row, dict):
#     for room, dict_vals in dict.items():
#         if room == row['Room']:
#             max_val = max(dict_vals.values())
#             keys_with_max = [(k, entries_to_time_reg(max_val)) for k, v in dict_vals.items() if v == max_val] # for visual appeal
#             # keys_with_max = [(k, max_val) for k, v in dict_vals.items() if v == max_val] # for computation
#             if len(keys_with_max) == 1:
#                 return keys_with_max[0]
#             return keys_with_max
#     return 'N/A'

# rooms_df["Champions of the Practice Room"] = rooms_df.apply(room_lb, args=(entries_by_room_by_person_wo_lessons,),axis=1)
# rooms_df

# # entries_by_room_by_person_wo_lessons

In [ ]:
# get the stats worksheet
stats_sheet = book.worksheet('Stats')

In [ ]:
# # individual stats

# # convert tuples to strings so it is parsable
# studio_stats_clean = studio_stats.copy()

# for col in studio_stats_clean.columns:
#     studio_stats_clean[col] = studio_stats_clean[col].apply(lambda x: str(x) if isinstance(x, (list, tuple)) else x)
    
# studio_stats_data = [studio_stats_clean.columns.values.tolist()] + studio_stats_clean.values.tolist()
# stats_sheet.update(studio_stats_data, 'A4')

In [ ]:
# # champs of the practice room

# rooms_df_clean = rooms_df.copy()
# for col in rooms_df_clean.columns:
#     rooms_df_clean[col] = rooms_df_clean[col].apply(lambda x: str(x) if isinstance(x, (list, tuple)) else x)

# rooms_df_data = [rooms_df_clean.columns.values.tolist()] + rooms_df_clean.values.tolist()
# stats_sheet.update(rooms_df_data, 'J4')

In [ ]:
# # entries by grade

# # reset index
# entries_by_grade_clean = entries_by_grade.reset_index()

# entries_by_grade_data = [entries_by_grade_clean.columns.values.tolist()] + entries_by_grade_clean.values.tolist()
# stats_sheet.update(entries_by_grade_data, 'M4')

In [ ]:
# room stats

In [ ]:
# entries_by_day barplot
plt.bar(entries.groupby(['day']).size().index, entries.groupby(['day']).size())
plt.xlabel("Day")
plt.xticks(rotation = 90)
plt.ylabel("Number of Entries")
plt.title("Day vs. Number of Entries (Overall)")
plt.show()

In [ ]:
# # entries_by_person_by_day barplot
# name = "Nate Dreyfus"

# data = entries_by_person_by_day[name]

# sorted_items = sorted(data.items())  # sorts by timestamp

# x = [k for k, v in sorted_items]
# y = [v for k, v in sorted_items]

# plt.plot(x, y)
# plt.scatter(x, y)
# plt.xlabel("Day")
# plt.xticks(rotation=90)
# plt.ylabel("Number of Entries")
# plt.title("Day vs. Number of Entries for " + name)
# plt.show()

In [ ]:
# import matplotlib.pyplot as plt
# import matplotlib.dates as mdates

# fig, ax = plt.subplots(figsize=(10, 6))

# for name, data in entries_by_person_by_day.items():
#     if (name == "Nate Dreyfus") or (name not in studio_names):
#         continue

#     # sort by date
#     sorted_items = sorted(data.items())
#     x = [k for k, v in sorted_items]  # timestamps
#     y = [v for k, v in sorted_items]  # values

#     ax.plot(x, y, linewidth=1.5, label=name)

# # ---- formatting ----
# ax.set_title("literally every entry ever by day")
# ax.set_xlabel("Date")
# ax.set_ylabel("Minutes Practiced")

# # better date formatting
# ax.xaxis.set_major_locator(mdates.WeekdayLocator(interval=1))   # tick every week
# ax.xaxis.set_major_formatter(mdates.DateFormatter('%m-%d'))

# plt.xticks(rotation=45)

# ax.legend()
# ax.grid(True)

# plt.tight_layout()
# plt.show()

In [ ]:
# entries_by_room barplot
plt.bar(entries.groupby(['room']).size().index, entries.groupby(['room']).size())
plt.xlabel("Room")
plt.ylabel("Number of Entries")
plt.title("Room vs. Number of Entries")
plt.show()

In [ ]:
# entries_by_room_wo_lessons barplot
plt.bar(entries[entries["is_lesson"] == False].groupby(['room']).size().index, entries[entries["is_lesson"] == False].groupby(['room']).size())
plt.xlabel("Room")
plt.ylabel("Number of Entries")
plt.title("Room vs. Number of Entries (w/o lessons)")
plt.show()

In [ ]:
# entries_by_grade barplot
plt.bar(entries_by_grade.index, entries_by_grade["Entries"])
plt.xlabel("Grade Level")
plt.xticks(rotation = 25)
plt.ylabel("Average Number of Entries")
plt.title("Grade Level vs. Number of Entries")
plt.savefig('grade_vs_avg.png', bbox_inches='tight')
plt.show()

In [ ]:
# entries_by_grade barplot
plt.bar(entries_by_grade.index, entries_by_grade["avg"])
plt.xlabel("Grade Level")
plt.xticks(rotation = 25)
plt.ylabel("Average Number of Entries")
plt.title("Grade Level vs. Average Number of Entries")
plt.savefig('grade_vs_avg.png', bbox_inches='tight')
plt.show()

In [ ]:
entries.groupby(["person","day"]).size()["Ravlin Frantz"]

In [ ]:
# entries by [person] by day

person = "Aaron Dieter"

plt.bar(entries.groupby(["person","day"]).size()[person].index, entries.groupby(["person","day"]).size()[person])
plt.xlabel("Person")
plt.xticks(rotation = 90)
plt.ylabel("Number of Entries")
plt.title(person + " vs. Number of Entries")
plt.show()

In [ ]:
plt.bar(entries.groupby(["person"]).size().index, entries.groupby(["person"]).size())
plt.xlabel("Person")
plt.xticks(rotation = 90)
plt.ylabel("Number of Entries")
plt.title("Person vs. Number of Entries")
plt.show()

In [ ]:
# predict occupancy of rooms: "Will 1401 be occupied at Tuesday 3:00 PM?"
# binary classification

# data collection/cleaning
# create datetime object with day and time combined
# entries["datetime"] = pd.to_datetime(entries["day"]) + pd.to_timedelta(pd.to_datetime(entries["time"], format="%I:%M %p").dt.strftime('%H:%M:%S'))

# get full range/potential times
times = pd.date_range(
    start=entries["datetime"].min(),
    end=entries["datetime"].max(),
    freq="15min"
)

# filter so only between 7am and 11pm
times = times[times.indexer_between_time("07:00", "23:00")]

# create df of times and rooms (Cartesian product)
full_schedule = (
    pd.MultiIndex
      .from_product([times, rooms],
                    names=["datetime", "room"])
      .to_frame(index=False)
)

# occupied column
entries["occupied"] = 1

# merge into full dataset
dataset = full_schedule.merge(
    entries[["datetime", "room", "occupied"]],
    on=["datetime", "room"],
    how="left"
)

# NaN values (non-entries) become 0
dataset["occupied"] = dataset["occupied"].fillna(0).astype(int)

In [ ]:
dataset

In [ ]:
# Sort
dataset = dataset.sort_values(["room", "datetime"])

In [ ]:
# Basic time features
dataset["hour"] = dataset["datetime"].dt.hour
dataset["weekday"] = dataset["datetime"].dt.dayofweek
dataset["is_weekend"] = ((dataset["weekday"] == 5) | (dataset["weekday"] == 6)).astype(int)

In [ ]:
# Historical occupancy features

# previous timeslot occupied
previous = dataset.groupby("room")["datetime"].diff()

dataset["occupied_previous"] = (dataset.groupby("room")["occupied"].shift(1))

dataset.loc[previous != pd.Timedelta(minutes=15), "occupied_previous"] = pd.NA # 7am edge case

# occupied 1hr ago
hr_ago = dataset[["datetime", "room", "occupied"]].copy()

hr_ago["datetime"] += pd.Timedelta(hours=1)

hr_ago = hr_ago.rename(columns={"occupied": "occupied_1hr_ago"})

dataset = dataset.merge(
    hr_ago,
    on=["datetime", "room"],
    how="left"
)

# occupied yesterday
previous_day = dataset[["datetime", "room", "occupied"]].copy()

previous_day["datetime"] += pd.Timedelta(days=1)

previous_day = previous_day.rename(columns={"occupied": "occupied_yesterday"})

dataset = dataset.merge(
    previous_day,
    on=["datetime", "room"],
    how="left"
)

# occupied last week
previous_week = dataset[["datetime", "room", "occupied"]].copy()

previous_week["datetime"] += pd.Timedelta(days=7)

previous_week = previous_week.rename(columns={"occupied": "occupied_last_week"})

dataset = dataset.merge(
    previous_week,
    on=["datetime", "room"],
    how="left"
)

In [ ]:
# using only rows that have all of the historical data
model_data = dataset.dropna(subset=["occupied_previous", "occupied_1hr_ago", "occupied_yesterday", "occupied_last_week"])
# model_data.isna().sum()

In [ ]:
features = ["hour", "weekday", "is_weekend", "occupied_previous", "occupied_1hr_ago", "occupied_yesterday", "occupied_last_week", "room"]

In [ ]:
# train and test split by time (50/50)
split_date = model_data["datetime"].median()

train = model_data[model_data["datetime"] < split_date]

test = model_data[model_data["datetime"] >= split_date]

In [ ]:
# train/test

X_train = pd.get_dummies(
    train[features],
    columns=["room"]
)

X_test = pd.get_dummies(
    test[features],
    columns=["room"]
)

# align X_train and X_test
X_train, X_test = X_train.align(
    X_test,
    join="left",
    axis=1,
    fill_value=0
)

y_train = train["occupied"]
y_test = test["occupied"]

# X_train

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

In [ ]:
model.fit(X_train, y_train)

In [ ]:
predictions = model.predict(X_test)
predictions

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, predictions)

print(accuracy)

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, predictions))

In [ ]:
# probabilities
probabilities = model.predict_proba(X_test)

occupancy_probability = model.predict_proba(X_test)[:, 1]

In [ ]:
# coefficients
coefficients = pd.Series(
    model.coef_[0],
    index=X_train.columns
)

print(coefficients.sort_values())

In [ ]:
# confusion matrix

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

cm = confusion_matrix(y_test, predictions)

print(cm)

In [ ]:
# Random Forest model
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

rf_predictions = rf_model.predict(X_test)

print(classification_report(y_test, rf_predictions))

In [ ]:
# RF feature importance

importance = pd.Series(
    rf_model.feature_importances_,
    index=X_train.columns
)

print(importance.sort_values(ascending=False))

In [ ]:
importance.sort_values().plot(
    kind="barh",
    figsize=(10, 8)
)

plt.xlabel("Feature Importance")
plt.title("Random Forest Feature Importance")
plt.show()

In [ ]:
# Save dataset

# change date for every use

dataset.to_csv(
    "dataset/dataset-8_22_26.csv",
    index=False
)